"""The teardown reporting protocol, shared by every executor substrate.

A teardown script is generated by
:meth:`~sparkrun.orchestration.executors._base.Executor.teardown_script` and
run on the target host.  Its *exit code* answers "did everything named
actually go away?" and this module defines how it reports **how many** things
it removed: a single ``sparkrun_removed=<n>`` line on stdout, read back by
:func:`parse_teardown_removed`.

The count exists because the obvious alternative — assuming one container per
host — over-reports every teardown that targeted candidate names which were
never there (``Executor.enumerate_containers`` emits the solo / head / worker /
node_N shapes and lets the substrate say which exist).  A caller that prints
"stopped 3 containers" when it stopped one is the same class of lie as a
teardown that reports success without checking.

This lives in its own leaf module rather than in ``orchestration.docker``
because it is substrate-agnostic: the ``local`` executor's pidfile teardown and
a provider executor's control-plane teardown report through it identically.
"""

from __future__ import annotations

TEARDOWN_REMOVED_MARKER = "sparkrun_removed="


def parse_teardown_removed(stdout: str) -> int:
    """Read the ``sparkrun_removed=<n>`` count out of teardown stdout.

    Scans from the end, so when several teardown scripts' outputs are
    concatenated (one host, several executors — see
    :func:`~sparkrun.orchestration.primitives.merge_teardown_results`) the
    caller-appended total wins over the per-executor sections above it.

    Returns 0 when the marker is absent or unparseable — an unknown count is
    reported as "removed nothing", never as an optimistic guess.
    """
    for line in reversed(stdout.splitlines()):
        line = line.strip()
        if line.startswith(TEARDOWN_REMOVED_MARKER):
            try:
                return int(line[len(TEARDOWN_REMOVED_MARKER) :])
            except ValueError:
                return 0
    return 0


def format_teardown_removed(count: int) -> str:
    """Render the marker line for *count* (the emit peer of the parser)."""
    return "%s%d" % (TEARDOWN_REMOVED_MARKER, int(count))


__all__ = ["TEARDOWN_REMOVED_MARKER", "format_teardown_removed", "parse_teardown_removed"]
